# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-03 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=200)),
                ('grad', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('git', models.CharField(max_length=200)),
                ('introduce', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('git', models.CharField(max_length=200)),
                ('sns', models.CharField(max_length=200)),
                ('student_id', models.IntegerField(default=0)),
                ('phone_num', models.IntegerField(default=0)),
            ],
        ),
    ]
