# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('git', models.CharField(max_length=200)),
                ('sns', models.CharField(max_length=200)),
                ('student_id', models.IntegerField(default=0)),
                ('phone_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Recruit_list',
            new_name='Choice',
        ),
        migrations.DeleteModel(
            name='Member_list',
        ),
    ]
